import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';

import { DataLakeServiceClient } from '@azure/storage-file-datalake';
import { AccessTokenCredential } from './AccessTokenCredential';

@Component({
  selector: 'app-home',
  templateUrl: './home.component.html',
  styleUrls: ['./home.component.scss']
})
export class HomeComponent implements OnInit {

  constructor(private router: Router) { }

  ngOnInit(): void {
    const account = 'test';
    const token = 'ABCD'; // This token is generated by AD OAuth flow
    const expiresOn = 1;
    const credentials = new AccessTokenCredential(token, expiresOn);
    const datalakeServiceClient = new DataLakeServiceClient(
      `https://${account}.dfs.core.windows.net`,
      credentials
    );
  }

}
